//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

/** @hidden */
public class _MasterCallbackPrxI extends com.zeroc.Ice._ObjectPrxI implements MasterCallbackPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
