//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class Arc implements java.lang.Cloneable,
                            java.io.Serializable
{
    public long originStopId;

    public long destinationStopId;

    public int lineId;

    public int orientation;

    public Arc()
    {
    }

    public Arc(long originStopId, long destinationStopId, int lineId, int orientation)
    {
        this.originStopId = originStopId;
        this.destinationStopId = destinationStopId;
        this.lineId = lineId;
        this.orientation = orientation;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Arc r = null;
        if(rhs instanceof Arc)
        {
            r = (Arc)rhs;
        }

        if(r != null)
        {
            if(this.originStopId != r.originStopId)
            {
                return false;
            }
            if(this.destinationStopId != r.destinationStopId)
            {
                return false;
            }
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::Arc");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, originStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destinationStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        return h_;
    }

    public Arc clone()
    {
        Arc c = null;
        try
        {
            c = (Arc)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.originStopId);
        ostr.writeLong(this.destinationStopId);
        ostr.writeInt(this.lineId);
        ostr.writeInt(this.orientation);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.originStopId = istr.readLong();
        this.destinationStopId = istr.readLong();
        this.lineId = istr.readInt();
        this.orientation = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Arc v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Arc ice_read(com.zeroc.Ice.InputStream istr)
    {
        Arc v = new Arc();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Arc> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Arc v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(24);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Arc> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Arc.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Arc _nullMarshalValue = new Arc();

    /** @hidden */
    public static final long serialVersionUID = 8103528508127046957L;
}
