//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class ArcSpeed implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public long originStopId;

    public long destinationStopId;

    public int lineId;

    public int orientation;

    public double averageSpeed;

    public int sampleCount;

    public double distance;

    public double averageTime;

    public ArcSpeed()
    {
    }

    public ArcSpeed(long originStopId, long destinationStopId, int lineId, int orientation, double averageSpeed, int sampleCount, double distance, double averageTime)
    {
        this.originStopId = originStopId;
        this.destinationStopId = destinationStopId;
        this.lineId = lineId;
        this.orientation = orientation;
        this.averageSpeed = averageSpeed;
        this.sampleCount = sampleCount;
        this.distance = distance;
        this.averageTime = averageTime;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ArcSpeed r = null;
        if(rhs instanceof ArcSpeed)
        {
            r = (ArcSpeed)rhs;
        }

        if(r != null)
        {
            if(this.originStopId != r.originStopId)
            {
                return false;
            }
            if(this.destinationStopId != r.destinationStopId)
            {
                return false;
            }
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }
            if(this.averageSpeed != r.averageSpeed)
            {
                return false;
            }
            if(this.sampleCount != r.sampleCount)
            {
                return false;
            }
            if(this.distance != r.distance)
            {
                return false;
            }
            if(this.averageTime != r.averageTime)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::ArcSpeed");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, originStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, destinationStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, averageSpeed);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, sampleCount);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, distance);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, averageTime);
        return h_;
    }

    public ArcSpeed clone()
    {
        ArcSpeed c = null;
        try
        {
            c = (ArcSpeed)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.originStopId);
        ostr.writeLong(this.destinationStopId);
        ostr.writeInt(this.lineId);
        ostr.writeInt(this.orientation);
        ostr.writeDouble(this.averageSpeed);
        ostr.writeInt(this.sampleCount);
        ostr.writeDouble(this.distance);
        ostr.writeDouble(this.averageTime);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.originStopId = istr.readLong();
        this.destinationStopId = istr.readLong();
        this.lineId = istr.readInt();
        this.orientation = istr.readInt();
        this.averageSpeed = istr.readDouble();
        this.sampleCount = istr.readInt();
        this.distance = istr.readDouble();
        this.averageTime = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ArcSpeed v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ArcSpeed ice_read(com.zeroc.Ice.InputStream istr)
    {
        ArcSpeed v = new ArcSpeed();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ArcSpeed> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ArcSpeed v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(52);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<ArcSpeed> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(ArcSpeed.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ArcSpeed _nullMarshalValue = new ArcSpeed();

    /** @hidden */
    public static final long serialVersionUID = -3160854576720604162L;
}
