//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class DataNotFoundException extends com.zeroc.Ice.UserException
{
    public DataNotFoundException()
    {
        this.message = "";
    }

    public DataNotFoundException(Throwable cause)
    {
        super(cause);
        this.message = "";
    }

    public DataNotFoundException(String message)
    {
        this.message = message;
    }

    public DataNotFoundException(String message, Throwable cause)
    {
        super(cause);
        this.message = message;
    }

    public String ice_id()
    {
        return "::MIO::DataNotFoundException";
    }

    public String message;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::MIO::DataNotFoundException", -1, true);
        ostr_.writeString(message);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        message = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = 890834585014460136L;
}
