//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class Datagram implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public int eventType;

    public String registerDate;

    public long stopId;

    public int odometer;

    public double latitude;

    public double longitude;

    public int taskId;

    public int lineId;

    public int tripId;

    public long unknown1;

    public String datagramDate;

    public int busId;

    public Datagram()
    {
        this.registerDate = "";
        this.datagramDate = "";
    }

    public Datagram(int eventType, String registerDate, long stopId, int odometer, double latitude, double longitude, int taskId, int lineId, int tripId, long unknown1, String datagramDate, int busId)
    {
        this.eventType = eventType;
        this.registerDate = registerDate;
        this.stopId = stopId;
        this.odometer = odometer;
        this.latitude = latitude;
        this.longitude = longitude;
        this.taskId = taskId;
        this.lineId = lineId;
        this.tripId = tripId;
        this.unknown1 = unknown1;
        this.datagramDate = datagramDate;
        this.busId = busId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Datagram r = null;
        if(rhs instanceof Datagram)
        {
            r = (Datagram)rhs;
        }

        if(r != null)
        {
            if(this.eventType != r.eventType)
            {
                return false;
            }
            if(this.registerDate != r.registerDate)
            {
                if(this.registerDate == null || r.registerDate == null || !this.registerDate.equals(r.registerDate))
                {
                    return false;
                }
            }
            if(this.stopId != r.stopId)
            {
                return false;
            }
            if(this.odometer != r.odometer)
            {
                return false;
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }
            if(this.taskId != r.taskId)
            {
                return false;
            }
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.tripId != r.tripId)
            {
                return false;
            }
            if(this.unknown1 != r.unknown1)
            {
                return false;
            }
            if(this.datagramDate != r.datagramDate)
            {
                if(this.datagramDate == null || r.datagramDate == null || !this.datagramDate.equals(r.datagramDate))
                {
                    return false;
                }
            }
            if(this.busId != r.busId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::Datagram");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, eventType);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, registerDate);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, odometer);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, tripId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, unknown1);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, datagramDate);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, busId);
        return h_;
    }

    public Datagram clone()
    {
        Datagram c = null;
        try
        {
            c = (Datagram)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.eventType);
        ostr.writeString(this.registerDate);
        ostr.writeLong(this.stopId);
        ostr.writeInt(this.odometer);
        ostr.writeDouble(this.latitude);
        ostr.writeDouble(this.longitude);
        ostr.writeInt(this.taskId);
        ostr.writeInt(this.lineId);
        ostr.writeInt(this.tripId);
        ostr.writeLong(this.unknown1);
        ostr.writeString(this.datagramDate);
        ostr.writeInt(this.busId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.eventType = istr.readInt();
        this.registerDate = istr.readString();
        this.stopId = istr.readLong();
        this.odometer = istr.readInt();
        this.latitude = istr.readDouble();
        this.longitude = istr.readDouble();
        this.taskId = istr.readInt();
        this.lineId = istr.readInt();
        this.tripId = istr.readInt();
        this.unknown1 = istr.readLong();
        this.datagramDate = istr.readString();
        this.busId = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Datagram v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Datagram ice_read(com.zeroc.Ice.InputStream istr)
    {
        Datagram v = new Datagram();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Datagram> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Datagram v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Datagram> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Datagram.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Datagram _nullMarshalValue = new Datagram();

    /** @hidden */
    public static final long serialVersionUID = 9015488596074947093L;
}
