//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class GraphInfo implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int totalRoutes;

    public int totalStops;

    public int totalArcs;

    public Stop[] stops;

    public LineStop[] lineStops;

    public GraphInfo()
    {
    }

    public GraphInfo(int totalRoutes, int totalStops, int totalArcs, Stop[] stops, LineStop[] lineStops)
    {
        this.totalRoutes = totalRoutes;
        this.totalStops = totalStops;
        this.totalArcs = totalArcs;
        this.stops = stops;
        this.lineStops = lineStops;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        GraphInfo r = null;
        if(rhs instanceof GraphInfo)
        {
            r = (GraphInfo)rhs;
        }

        if(r != null)
        {
            if(this.totalRoutes != r.totalRoutes)
            {
                return false;
            }
            if(this.totalStops != r.totalStops)
            {
                return false;
            }
            if(this.totalArcs != r.totalArcs)
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.stops, r.stops))
            {
                return false;
            }
            if(!java.util.Arrays.equals(this.lineStops, r.lineStops))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::GraphInfo");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalRoutes);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalStops);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, totalArcs);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stops);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineStops);
        return h_;
    }

    public GraphInfo clone()
    {
        GraphInfo c = null;
        try
        {
            c = (GraphInfo)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.totalRoutes);
        ostr.writeInt(this.totalStops);
        ostr.writeInt(this.totalArcs);
        StopListHelper.write(ostr, this.stops);
        LineStopListHelper.write(ostr, this.lineStops);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.totalRoutes = istr.readInt();
        this.totalStops = istr.readInt();
        this.totalArcs = istr.readInt();
        this.stops = StopListHelper.read(istr);
        this.lineStops = LineStopListHelper.read(istr);
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, GraphInfo v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public GraphInfo ice_read(com.zeroc.Ice.InputStream istr)
    {
        GraphInfo v = new GraphInfo();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<GraphInfo> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, GraphInfo v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<GraphInfo> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(GraphInfo.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final GraphInfo _nullMarshalValue = new GraphInfo();

    /** @hidden */
    public static final long serialVersionUID = 1649241835025673003L;
}
