//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

/**
 * Helper class for marshaling/unmarshaling LineStopList.
 **/
public final class LineStopListHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, LineStop[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                LineStop.ice_write(ostr, v[i0]);
            }
        }
    }

    public static LineStop[] read(com.zeroc.Ice.InputStream istr)
    {
        final LineStop[] v;
        final int len0 = istr.readAndCheckSeqSize(28);
        v = new LineStop[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = LineStop.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LineStop[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, LineStop[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 28 + 5 : optSize * 28 + 1);
            LineStopListHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<LineStop[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            LineStop[] v;
            v = LineStopListHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
