//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class LineStop implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public long lineStopId;

    public int stopSequence;

    public int orientation;

    public int lineId;

    public long stopId;

    public LineStop()
    {
    }

    public LineStop(long lineStopId, int stopSequence, int orientation, int lineId, long stopId)
    {
        this.lineStopId = lineStopId;
        this.stopSequence = stopSequence;
        this.orientation = orientation;
        this.lineId = lineId;
        this.stopId = stopId;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        LineStop r = null;
        if(rhs instanceof LineStop)
        {
            r = (LineStop)rhs;
        }

        if(r != null)
        {
            if(this.lineStopId != r.lineStopId)
            {
                return false;
            }
            if(this.stopSequence != r.stopSequence)
            {
                return false;
            }
            if(this.orientation != r.orientation)
            {
                return false;
            }
            if(this.lineId != r.lineId)
            {
                return false;
            }
            if(this.stopId != r.stopId)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::LineStop");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineStopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopSequence);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, orientation);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, lineId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopId);
        return h_;
    }

    public LineStop clone()
    {
        LineStop c = null;
        try
        {
            c = (LineStop)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.lineStopId);
        ostr.writeInt(this.stopSequence);
        ostr.writeInt(this.orientation);
        ostr.writeInt(this.lineId);
        ostr.writeLong(this.stopId);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.lineStopId = istr.readLong();
        this.stopSequence = istr.readInt();
        this.orientation = istr.readInt();
        this.lineId = istr.readInt();
        this.stopId = istr.readLong();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, LineStop v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public LineStop ice_read(com.zeroc.Ice.InputStream istr)
    {
        LineStop v = new LineStop();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<LineStop> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, LineStop v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(28);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<LineStop> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(LineStop.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final LineStop _nullMarshalValue = new LineStop();

    /** @hidden */
    public static final long serialVersionUID = 7473586202805653101L;
}
