//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public interface MasterCoordinatorPrx extends com.zeroc.Ice.ObjectPrx
{
    default String startProcessing(String dataFilePath, int numTasks)
        throws ProcessingException
    {
        return startProcessing(dataFilePath, numTasks, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String startProcessing(String dataFilePath, int numTasks, java.util.Map<String, String> context)
        throws ProcessingException
    {
        try
        {
            return _iceI_startProcessingAsync(dataFilePath, numTasks, context, true).waitForResponseOrUserEx();
        }
        catch(ProcessingException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> startProcessingAsync(String dataFilePath, int numTasks)
    {
        return _iceI_startProcessingAsync(dataFilePath, numTasks, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> startProcessingAsync(String dataFilePath, int numTasks, java.util.Map<String, String> context)
    {
        return _iceI_startProcessingAsync(dataFilePath, numTasks, context, false);
    }

    /**
     * @hidden
     * @param iceP_dataFilePath -
     * @param iceP_numTasks -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_startProcessingAsync(String iceP_dataFilePath, int iceP_numTasks, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startProcessing", null, sync, _iceE_startProcessing);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_dataFilePath);
                     ostr.writeInt(iceP_numTasks);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_startProcessing =
    {
        ProcessingException.class
    };

    default void registerWorker(WorkerPrx workerProxy, String workerId)
    {
        registerWorker(workerProxy, workerId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerWorker(WorkerPrx workerProxy, String workerId, java.util.Map<String, String> context)
    {
        _iceI_registerWorkerAsync(workerProxy, workerId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerWorkerAsync(WorkerPrx workerProxy, String workerId)
    {
        return _iceI_registerWorkerAsync(workerProxy, workerId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerWorkerAsync(WorkerPrx workerProxy, String workerId, java.util.Map<String, String> context)
    {
        return _iceI_registerWorkerAsync(workerProxy, workerId, context, false);
    }

    /**
     * @hidden
     * @param iceP_workerProxy -
     * @param iceP_workerId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerWorkerAsync(WorkerPrx iceP_workerProxy, String iceP_workerId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerWorker", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_workerProxy);
                     ostr.writeString(iceP_workerId);
                 }, null);
        return f;
    }

    default String getProcessingStatus(String jobId)
    {
        return getProcessingStatus(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getProcessingStatus(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getProcessingStatusAsync(jobId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getProcessingStatusAsync(String jobId)
    {
        return _iceI_getProcessingStatusAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getProcessingStatusAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getProcessingStatusAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getProcessingStatusAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getProcessingStatus", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default ArcSpeed[] getResults(String jobId)
        throws DataNotFoundException
    {
        return getResults(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcSpeed[] getResults(String jobId, java.util.Map<String, String> context)
        throws DataNotFoundException
    {
        try
        {
            return _iceI_getResultsAsync(jobId, context, true).waitForResponseOrUserEx();
        }
        catch(DataNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getResultsAsync(String jobId)
    {
        return _iceI_getResultsAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getResultsAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getResultsAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> _iceI_getResultsAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getResults", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getResults);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, istr -> {
                     ArcSpeed[] ret;
                     ret = ArcSpeedListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getResults =
    {
        DataNotFoundException.class
    };

    default void cancelProcessing(String jobId)
    {
        cancelProcessing(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void cancelProcessing(String jobId, java.util.Map<String, String> context)
    {
        _iceI_cancelProcessingAsync(jobId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> cancelProcessingAsync(String jobId)
    {
        return _iceI_cancelProcessingAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> cancelProcessingAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_cancelProcessingAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_cancelProcessingAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "cancelProcessing", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterCoordinatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), MasterCoordinatorPrx.class, _MasterCoordinatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterCoordinatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), MasterCoordinatorPrx.class, _MasterCoordinatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterCoordinatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), MasterCoordinatorPrx.class, _MasterCoordinatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static MasterCoordinatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), MasterCoordinatorPrx.class, _MasterCoordinatorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static MasterCoordinatorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, MasterCoordinatorPrx.class, _MasterCoordinatorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static MasterCoordinatorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, MasterCoordinatorPrx.class, _MasterCoordinatorPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default MasterCoordinatorPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (MasterCoordinatorPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default MasterCoordinatorPrx ice_adapterId(String newAdapterId)
    {
        return (MasterCoordinatorPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default MasterCoordinatorPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (MasterCoordinatorPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default MasterCoordinatorPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (MasterCoordinatorPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default MasterCoordinatorPrx ice_invocationTimeout(int newTimeout)
    {
        return (MasterCoordinatorPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default MasterCoordinatorPrx ice_connectionCached(boolean newCache)
    {
        return (MasterCoordinatorPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default MasterCoordinatorPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (MasterCoordinatorPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MasterCoordinatorPrx ice_secure(boolean b)
    {
        return (MasterCoordinatorPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default MasterCoordinatorPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (MasterCoordinatorPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default MasterCoordinatorPrx ice_preferSecure(boolean b)
    {
        return (MasterCoordinatorPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default MasterCoordinatorPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (MasterCoordinatorPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default MasterCoordinatorPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (MasterCoordinatorPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default MasterCoordinatorPrx ice_collocationOptimized(boolean b)
    {
        return (MasterCoordinatorPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default MasterCoordinatorPrx ice_twoway()
    {
        return (MasterCoordinatorPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default MasterCoordinatorPrx ice_oneway()
    {
        return (MasterCoordinatorPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default MasterCoordinatorPrx ice_batchOneway()
    {
        return (MasterCoordinatorPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default MasterCoordinatorPrx ice_datagram()
    {
        return (MasterCoordinatorPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default MasterCoordinatorPrx ice_batchDatagram()
    {
        return (MasterCoordinatorPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default MasterCoordinatorPrx ice_compress(boolean co)
    {
        return (MasterCoordinatorPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default MasterCoordinatorPrx ice_timeout(int t)
    {
        return (MasterCoordinatorPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default MasterCoordinatorPrx ice_connectionId(String connectionId)
    {
        return (MasterCoordinatorPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default MasterCoordinatorPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (MasterCoordinatorPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MIO::MasterCoordinator";
    }
}
