//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class ProcessingTask implements java.lang.Cloneable,
                                       java.io.Serializable
{
    public int taskId;

    public long startOffset;

    public long endOffset;

    public String filePath;

    public String[] datagramLines;

    public ProcessingTask()
    {
        this.filePath = "";
    }

    public ProcessingTask(int taskId, long startOffset, long endOffset, String filePath, String[] datagramLines)
    {
        this.taskId = taskId;
        this.startOffset = startOffset;
        this.endOffset = endOffset;
        this.filePath = filePath;
        this.datagramLines = datagramLines;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ProcessingTask r = null;
        if(rhs instanceof ProcessingTask)
        {
            r = (ProcessingTask)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                return false;
            }
            if(this.startOffset != r.startOffset)
            {
                return false;
            }
            if(this.endOffset != r.endOffset)
            {
                return false;
            }
            if(this.filePath != r.filePath)
            {
                if(this.filePath == null || r.filePath == null || !this.filePath.equals(r.filePath))
                {
                    return false;
                }
            }
            if(!java.util.Arrays.equals(this.datagramLines, r.datagramLines))
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::ProcessingTask");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, startOffset);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, endOffset);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, filePath);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, datagramLines);
        return h_;
    }

    public ProcessingTask clone()
    {
        ProcessingTask c = null;
        try
        {
            c = (ProcessingTask)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.taskId);
        ostr.writeLong(this.startOffset);
        ostr.writeLong(this.endOffset);
        ostr.writeString(this.filePath);
        ostr.writeStringSeq(this.datagramLines);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readInt();
        this.startOffset = istr.readLong();
        this.endOffset = istr.readLong();
        this.filePath = istr.readString();
        this.datagramLines = istr.readStringSeq();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ProcessingTask v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ProcessingTask ice_read(com.zeroc.Ice.InputStream istr)
    {
        ProcessingTask v = new ProcessingTask();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ProcessingTask> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ProcessingTask v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ProcessingTask> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ProcessingTask.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ProcessingTask _nullMarshalValue = new ProcessingTask();

    /** @hidden */
    public static final long serialVersionUID = 3539082435333626417L;
}
