//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class ProcessingResult implements java.lang.Cloneable,
                                         java.io.Serializable
{
    public int taskId;

    public java.util.Map<java.lang.String, ArcSpeed> partialResults;

    public int processedRecords;

    public double processingTime;

    public boolean success;

    public String errorMessage;

    public ProcessingResult()
    {
        this.errorMessage = "";
    }

    public ProcessingResult(int taskId, java.util.Map<java.lang.String, ArcSpeed> partialResults, int processedRecords, double processingTime, boolean success, String errorMessage)
    {
        this.taskId = taskId;
        this.partialResults = partialResults;
        this.processedRecords = processedRecords;
        this.processingTime = processingTime;
        this.success = success;
        this.errorMessage = errorMessage;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        ProcessingResult r = null;
        if(rhs instanceof ProcessingResult)
        {
            r = (ProcessingResult)rhs;
        }

        if(r != null)
        {
            if(this.taskId != r.taskId)
            {
                return false;
            }
            if(this.partialResults != r.partialResults)
            {
                if(this.partialResults == null || r.partialResults == null || !this.partialResults.equals(r.partialResults))
                {
                    return false;
                }
            }
            if(this.processedRecords != r.processedRecords)
            {
                return false;
            }
            if(this.processingTime != r.processingTime)
            {
                return false;
            }
            if(this.success != r.success)
            {
                return false;
            }
            if(this.errorMessage != r.errorMessage)
            {
                if(this.errorMessage == null || r.errorMessage == null || !this.errorMessage.equals(r.errorMessage))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::ProcessingResult");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, taskId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, partialResults);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processedRecords);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, processingTime);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, success);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, errorMessage);
        return h_;
    }

    public ProcessingResult clone()
    {
        ProcessingResult c = null;
        try
        {
            c = (ProcessingResult)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.taskId);
        ArcSpeedMapHelper.write(ostr, this.partialResults);
        ostr.writeInt(this.processedRecords);
        ostr.writeDouble(this.processingTime);
        ostr.writeBool(this.success);
        ostr.writeString(this.errorMessage);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.taskId = istr.readInt();
        this.partialResults = ArcSpeedMapHelper.read(istr);
        this.processedRecords = istr.readInt();
        this.processingTime = istr.readDouble();
        this.success = istr.readBool();
        this.errorMessage = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, ProcessingResult v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public ProcessingResult ice_read(com.zeroc.Ice.InputStream istr)
    {
        ProcessingResult v = new ProcessingResult();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<ProcessingResult> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, ProcessingResult v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<ProcessingResult> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(ProcessingResult.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final ProcessingResult _nullMarshalValue = new ProcessingResult();

    /** @hidden */
    public static final long serialVersionUID = -1645366405648422191L;
}
