//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public interface QueryService extends com.zeroc.Ice.Object
{
    ArcSpeed getArcSpeed(int lineId, long originStop, long destStop, int orientation, com.zeroc.Ice.Current current)
        throws DataNotFoundException;

    ArcSpeed[] getRouteSpeed(int lineId, int orientation, com.zeroc.Ice.Current current);

    ArcSpeed[] getZoneSpeeds(long[] stopIds, com.zeroc.Ice.Current current);

    String getSystemStatistics(com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::MIO::QueryService"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::MIO::QueryService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getArcSpeed(QueryService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_lineId;
        long iceP_originStop;
        long iceP_destStop;
        int iceP_orientation;
        iceP_lineId = istr.readInt();
        iceP_originStop = istr.readLong();
        iceP_destStop = istr.readLong();
        iceP_orientation = istr.readInt();
        inS.endReadParams();
        ArcSpeed ret = obj.getArcSpeed(iceP_lineId, iceP_originStop, iceP_destStop, iceP_orientation, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcSpeed.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getRouteSpeed(QueryService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        int iceP_lineId;
        int iceP_orientation;
        iceP_lineId = istr.readInt();
        iceP_orientation = istr.readInt();
        inS.endReadParams();
        ArcSpeed[] ret = obj.getRouteSpeed(iceP_lineId, iceP_orientation, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcSpeedListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getZoneSpeeds(QueryService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        long[] iceP_stopIds;
        iceP_stopIds = istr.readLongSeq();
        inS.endReadParams();
        ArcSpeed[] ret = obj.getZoneSpeeds(iceP_stopIds, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ArcSpeedListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getSystemStatistics(QueryService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        String ret = obj.getSystemStatistics(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        ostr.writeString(ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getArcSpeed",
        "getRouteSpeed",
        "getSystemStatistics",
        "getZoneSpeeds",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_getArcSpeed(this, in, current);
            }
            case 1:
            {
                return _iceD_getRouteSpeed(this, in, current);
            }
            case 2:
            {
                return _iceD_getSystemStatistics(this, in, current);
            }
            case 3:
            {
                return _iceD_getZoneSpeeds(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
