//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public interface QueryServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default ArcSpeed getArcSpeed(int lineId, long originStop, long destStop, int orientation)
        throws DataNotFoundException
    {
        return getArcSpeed(lineId, originStop, destStop, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcSpeed getArcSpeed(int lineId, long originStop, long destStop, int orientation, java.util.Map<String, String> context)
        throws DataNotFoundException
    {
        try
        {
            return _iceI_getArcSpeedAsync(lineId, originStop, destStop, orientation, context, true).waitForResponseOrUserEx();
        }
        catch(DataNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed> getArcSpeedAsync(int lineId, long originStop, long destStop, int orientation)
    {
        return _iceI_getArcSpeedAsync(lineId, originStop, destStop, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed> getArcSpeedAsync(int lineId, long originStop, long destStop, int orientation, java.util.Map<String, String> context)
    {
        return _iceI_getArcSpeedAsync(lineId, originStop, destStop, orientation, context, false);
    }

    /**
     * @hidden
     * @param iceP_lineId -
     * @param iceP_originStop -
     * @param iceP_destStop -
     * @param iceP_orientation -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcSpeed> _iceI_getArcSpeedAsync(int iceP_lineId, long iceP_originStop, long iceP_destStop, int iceP_orientation, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcSpeed> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getArcSpeed", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getArcSpeed);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_lineId);
                     ostr.writeLong(iceP_originStop);
                     ostr.writeLong(iceP_destStop);
                     ostr.writeInt(iceP_orientation);
                 }, istr -> {
                     ArcSpeed ret;
                     ret = ArcSpeed.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getArcSpeed =
    {
        DataNotFoundException.class
    };

    default ArcSpeed[] getRouteSpeed(int lineId, int orientation)
    {
        return getRouteSpeed(lineId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcSpeed[] getRouteSpeed(int lineId, int orientation, java.util.Map<String, String> context)
    {
        return _iceI_getRouteSpeedAsync(lineId, orientation, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getRouteSpeedAsync(int lineId, int orientation)
    {
        return _iceI_getRouteSpeedAsync(lineId, orientation, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getRouteSpeedAsync(int lineId, int orientation, java.util.Map<String, String> context)
    {
        return _iceI_getRouteSpeedAsync(lineId, orientation, context, false);
    }

    /**
     * @hidden
     * @param iceP_lineId -
     * @param iceP_orientation -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> _iceI_getRouteSpeedAsync(int iceP_lineId, int iceP_orientation, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getRouteSpeed", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_lineId);
                     ostr.writeInt(iceP_orientation);
                 }, istr -> {
                     ArcSpeed[] ret;
                     ret = ArcSpeedListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default ArcSpeed[] getZoneSpeeds(long[] stopIds)
    {
        return getZoneSpeeds(stopIds, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcSpeed[] getZoneSpeeds(long[] stopIds, java.util.Map<String, String> context)
    {
        return _iceI_getZoneSpeedsAsync(stopIds, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getZoneSpeedsAsync(long[] stopIds)
    {
        return _iceI_getZoneSpeedsAsync(stopIds, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getZoneSpeedsAsync(long[] stopIds, java.util.Map<String, String> context)
    {
        return _iceI_getZoneSpeedsAsync(stopIds, context, false);
    }

    /**
     * @hidden
     * @param iceP_stopIds -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> _iceI_getZoneSpeedsAsync(long[] iceP_stopIds, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getZoneSpeeds", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeLongSeq(iceP_stopIds);
                 }, istr -> {
                     ArcSpeed[] ret;
                     ret = ArcSpeedListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default String getSystemStatistics()
    {
        return getSystemStatistics(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getSystemStatistics(java.util.Map<String, String> context)
    {
        return _iceI_getSystemStatisticsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSystemStatisticsAsync()
    {
        return _iceI_getSystemStatisticsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSystemStatisticsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getSystemStatisticsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getSystemStatisticsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSystemStatistics", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static QueryServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), QueryServicePrx.class, _QueryServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static QueryServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), QueryServicePrx.class, _QueryServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static QueryServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), QueryServicePrx.class, _QueryServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static QueryServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), QueryServicePrx.class, _QueryServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static QueryServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, QueryServicePrx.class, _QueryServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static QueryServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, QueryServicePrx.class, _QueryServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default QueryServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (QueryServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default QueryServicePrx ice_adapterId(String newAdapterId)
    {
        return (QueryServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default QueryServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (QueryServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default QueryServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (QueryServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default QueryServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (QueryServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default QueryServicePrx ice_connectionCached(boolean newCache)
    {
        return (QueryServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default QueryServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (QueryServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default QueryServicePrx ice_secure(boolean b)
    {
        return (QueryServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default QueryServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (QueryServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default QueryServicePrx ice_preferSecure(boolean b)
    {
        return (QueryServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default QueryServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (QueryServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default QueryServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (QueryServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default QueryServicePrx ice_collocationOptimized(boolean b)
    {
        return (QueryServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default QueryServicePrx ice_twoway()
    {
        return (QueryServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default QueryServicePrx ice_oneway()
    {
        return (QueryServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default QueryServicePrx ice_batchOneway()
    {
        return (QueryServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default QueryServicePrx ice_datagram()
    {
        return (QueryServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default QueryServicePrx ice_batchDatagram()
    {
        return (QueryServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default QueryServicePrx ice_compress(boolean co)
    {
        return (QueryServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default QueryServicePrx ice_timeout(int t)
    {
        return (QueryServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default QueryServicePrx ice_connectionId(String connectionId)
    {
        return (QueryServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default QueryServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (QueryServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MIO::QueryService";
    }
}
