//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public interface ResultAggregatorPrx extends com.zeroc.Ice.ObjectPrx
{
    default void addPartialResult(String jobId, ProcessingResult result)
    {
        addPartialResult(jobId, result, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addPartialResult(String jobId, ProcessingResult result, java.util.Map<String, String> context)
    {
        _iceI_addPartialResultAsync(jobId, result, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> addPartialResultAsync(String jobId, ProcessingResult result)
    {
        return _iceI_addPartialResultAsync(jobId, result, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addPartialResultAsync(String jobId, ProcessingResult result, java.util.Map<String, String> context)
    {
        return _iceI_addPartialResultAsync(jobId, result, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param iceP_result -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addPartialResultAsync(String iceP_jobId, ProcessingResult iceP_result, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addPartialResult", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                     ProcessingResult.ice_write(ostr, iceP_result);
                 }, null);
        return f;
    }

    default ArcSpeed[] getFinalResults(String jobId)
        throws DataNotFoundException
    {
        return getFinalResults(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default ArcSpeed[] getFinalResults(String jobId, java.util.Map<String, String> context)
        throws DataNotFoundException
    {
        try
        {
            return _iceI_getFinalResultsAsync(jobId, context, true).waitForResponseOrUserEx();
        }
        catch(DataNotFoundException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getFinalResultsAsync(String jobId)
    {
        return _iceI_getFinalResultsAsync(jobId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<ArcSpeed[]> getFinalResultsAsync(String jobId, java.util.Map<String, String> context)
    {
        return _iceI_getFinalResultsAsync(jobId, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> _iceI_getFinalResultsAsync(String iceP_jobId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<ArcSpeed[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getFinalResults", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getFinalResults);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                 }, istr -> {
                     ArcSpeed[] ret;
                     ret = ArcSpeedListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getFinalResults =
    {
        DataNotFoundException.class
    };

    default void persistResults(String jobId, String outputPath)
        throws ProcessingException
    {
        persistResults(jobId, outputPath, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void persistResults(String jobId, String outputPath, java.util.Map<String, String> context)
        throws ProcessingException
    {
        try
        {
            _iceI_persistResultsAsync(jobId, outputPath, context, true).waitForResponseOrUserEx();
        }
        catch(ProcessingException ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> persistResultsAsync(String jobId, String outputPath)
    {
        return _iceI_persistResultsAsync(jobId, outputPath, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> persistResultsAsync(String jobId, String outputPath, java.util.Map<String, String> context)
    {
        return _iceI_persistResultsAsync(jobId, outputPath, context, false);
    }

    /**
     * @hidden
     * @param iceP_jobId -
     * @param iceP_outputPath -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_persistResultsAsync(String iceP_jobId, String iceP_outputPath, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "persistResults", null, sync, _iceE_persistResults);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_jobId);
                     ostr.writeString(iceP_outputPath);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_persistResults =
    {
        ProcessingException.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ResultAggregatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ResultAggregatorPrx.class, _ResultAggregatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ResultAggregatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ResultAggregatorPrx.class, _ResultAggregatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ResultAggregatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ResultAggregatorPrx.class, _ResultAggregatorPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ResultAggregatorPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ResultAggregatorPrx.class, _ResultAggregatorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ResultAggregatorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ResultAggregatorPrx.class, _ResultAggregatorPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ResultAggregatorPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ResultAggregatorPrx.class, _ResultAggregatorPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ResultAggregatorPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ResultAggregatorPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ResultAggregatorPrx ice_adapterId(String newAdapterId)
    {
        return (ResultAggregatorPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ResultAggregatorPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ResultAggregatorPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ResultAggregatorPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ResultAggregatorPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ResultAggregatorPrx ice_invocationTimeout(int newTimeout)
    {
        return (ResultAggregatorPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ResultAggregatorPrx ice_connectionCached(boolean newCache)
    {
        return (ResultAggregatorPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ResultAggregatorPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ResultAggregatorPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ResultAggregatorPrx ice_secure(boolean b)
    {
        return (ResultAggregatorPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ResultAggregatorPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ResultAggregatorPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ResultAggregatorPrx ice_preferSecure(boolean b)
    {
        return (ResultAggregatorPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ResultAggregatorPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ResultAggregatorPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ResultAggregatorPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ResultAggregatorPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ResultAggregatorPrx ice_collocationOptimized(boolean b)
    {
        return (ResultAggregatorPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ResultAggregatorPrx ice_twoway()
    {
        return (ResultAggregatorPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ResultAggregatorPrx ice_oneway()
    {
        return (ResultAggregatorPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ResultAggregatorPrx ice_batchOneway()
    {
        return (ResultAggregatorPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ResultAggregatorPrx ice_datagram()
    {
        return (ResultAggregatorPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ResultAggregatorPrx ice_batchDatagram()
    {
        return (ResultAggregatorPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ResultAggregatorPrx ice_compress(boolean co)
    {
        return (ResultAggregatorPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ResultAggregatorPrx ice_timeout(int t)
    {
        return (ResultAggregatorPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ResultAggregatorPrx ice_connectionId(String connectionId)
    {
        return (ResultAggregatorPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ResultAggregatorPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ResultAggregatorPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MIO::ResultAggregator";
    }
}
