//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

public class Stop implements java.lang.Cloneable,
                             java.io.Serializable
{
    public long stopId;

    public String shortName;

    public String longName;

    public double longitude;

    public double latitude;

    public Stop()
    {
        this.shortName = "";
        this.longName = "";
    }

    public Stop(long stopId, String shortName, String longName, double longitude, double latitude)
    {
        this.stopId = stopId;
        this.shortName = shortName;
        this.longName = longName;
        this.longitude = longitude;
        this.latitude = latitude;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Stop r = null;
        if(rhs instanceof Stop)
        {
            r = (Stop)rhs;
        }

        if(r != null)
        {
            if(this.stopId != r.stopId)
            {
                return false;
            }
            if(this.shortName != r.shortName)
            {
                if(this.shortName == null || r.shortName == null || !this.shortName.equals(r.shortName))
                {
                    return false;
                }
            }
            if(this.longName != r.longName)
            {
                if(this.longName == null || r.longName == null || !this.longName.equals(r.longName))
                {
                    return false;
                }
            }
            if(this.longitude != r.longitude)
            {
                return false;
            }
            if(this.latitude != r.latitude)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::MIO::Stop");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, stopId);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, shortName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longName);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, longitude);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, latitude);
        return h_;
    }

    public Stop clone()
    {
        Stop c = null;
        try
        {
            c = (Stop)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.stopId);
        ostr.writeString(this.shortName);
        ostr.writeString(this.longName);
        ostr.writeDouble(this.longitude);
        ostr.writeDouble(this.latitude);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.stopId = istr.readLong();
        this.shortName = istr.readString();
        this.longName = istr.readString();
        this.longitude = istr.readDouble();
        this.latitude = istr.readDouble();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Stop v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Stop ice_read(com.zeroc.Ice.InputStream istr)
    {
        Stop v = new Stop();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Stop> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Stop v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Stop> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Stop.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Stop _nullMarshalValue = new Stop();

    /** @hidden */
    public static final long serialVersionUID = -8924041527082625087L;
}
