//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `mio.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MIO;

/**
 * Broker de mensajes para pub/sub de datagramas.
 **/
public interface StreamBrokerPrx extends com.zeroc.Ice.ObjectPrx
{
    default void publish(Datagram datagram)
    {
        publish(datagram, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void publish(Datagram datagram, java.util.Map<String, String> context)
    {
        _iceI_publishAsync(datagram, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> publishAsync(Datagram datagram)
    {
        return _iceI_publishAsync(datagram, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> publishAsync(Datagram datagram, java.util.Map<String, String> context)
    {
        return _iceI_publishAsync(datagram, context, false);
    }

    /**
     * @hidden
     * @param iceP_datagram -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_publishAsync(Datagram iceP_datagram, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "publish", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     Datagram.ice_write(ostr, iceP_datagram);
                 }, null);
        return f;
    }

    default void publishBatch(Datagram[] datagrams)
    {
        publishBatch(datagrams, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void publishBatch(Datagram[] datagrams, java.util.Map<String, String> context)
    {
        _iceI_publishBatchAsync(datagrams, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> publishBatchAsync(Datagram[] datagrams)
    {
        return _iceI_publishBatchAsync(datagrams, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> publishBatchAsync(Datagram[] datagrams, java.util.Map<String, String> context)
    {
        return _iceI_publishBatchAsync(datagrams, context, false);
    }

    /**
     * @hidden
     * @param iceP_datagrams -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_publishBatchAsync(Datagram[] iceP_datagrams, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "publishBatch", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     DatagramSeqHelper.write(ostr, iceP_datagrams);
                 }, null);
        return f;
    }

    default void subscribe(StreamSubscriberPrx subscriber)
    {
        subscribe(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void subscribe(StreamSubscriberPrx subscriber, java.util.Map<String, String> context)
    {
        _iceI_subscribeAsync(subscriber, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeAsync(StreamSubscriberPrx subscriber)
    {
        return _iceI_subscribeAsync(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> subscribeAsync(StreamSubscriberPrx subscriber, java.util.Map<String, String> context)
    {
        return _iceI_subscribeAsync(subscriber, context, false);
    }

    /**
     * @hidden
     * @param iceP_subscriber -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_subscribeAsync(StreamSubscriberPrx iceP_subscriber, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "subscribe", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_subscriber);
                 }, null);
        return f;
    }

    default void unsubscribe(StreamSubscriberPrx subscriber)
    {
        unsubscribe(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void unsubscribe(StreamSubscriberPrx subscriber, java.util.Map<String, String> context)
    {
        _iceI_unsubscribeAsync(subscriber, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> unsubscribeAsync(StreamSubscriberPrx subscriber)
    {
        return _iceI_unsubscribeAsync(subscriber, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> unsubscribeAsync(StreamSubscriberPrx subscriber, java.util.Map<String, String> context)
    {
        return _iceI_unsubscribeAsync(subscriber, context, false);
    }

    /**
     * @hidden
     * @param iceP_subscriber -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_unsubscribeAsync(StreamSubscriberPrx iceP_subscriber, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "unsubscribe", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeProxy(iceP_subscriber);
                 }, null);
        return f;
    }

    default String getStats()
    {
        return getStats(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getStats(java.util.Map<String, String> context)
    {
        return _iceI_getStatsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getStatsAsync()
    {
        return _iceI_getStatsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getStatsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getStatsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getStatsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getStats", com.zeroc.Ice.OperationMode.Idempotent, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamBrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), StreamBrokerPrx.class, _StreamBrokerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamBrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), StreamBrokerPrx.class, _StreamBrokerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamBrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), StreamBrokerPrx.class, _StreamBrokerPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static StreamBrokerPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), StreamBrokerPrx.class, _StreamBrokerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static StreamBrokerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, StreamBrokerPrx.class, _StreamBrokerPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static StreamBrokerPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, StreamBrokerPrx.class, _StreamBrokerPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default StreamBrokerPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (StreamBrokerPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default StreamBrokerPrx ice_adapterId(String newAdapterId)
    {
        return (StreamBrokerPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default StreamBrokerPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (StreamBrokerPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default StreamBrokerPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (StreamBrokerPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default StreamBrokerPrx ice_invocationTimeout(int newTimeout)
    {
        return (StreamBrokerPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default StreamBrokerPrx ice_connectionCached(boolean newCache)
    {
        return (StreamBrokerPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default StreamBrokerPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (StreamBrokerPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StreamBrokerPrx ice_secure(boolean b)
    {
        return (StreamBrokerPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default StreamBrokerPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (StreamBrokerPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default StreamBrokerPrx ice_preferSecure(boolean b)
    {
        return (StreamBrokerPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default StreamBrokerPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (StreamBrokerPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default StreamBrokerPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (StreamBrokerPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default StreamBrokerPrx ice_collocationOptimized(boolean b)
    {
        return (StreamBrokerPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default StreamBrokerPrx ice_twoway()
    {
        return (StreamBrokerPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default StreamBrokerPrx ice_oneway()
    {
        return (StreamBrokerPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default StreamBrokerPrx ice_batchOneway()
    {
        return (StreamBrokerPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default StreamBrokerPrx ice_datagram()
    {
        return (StreamBrokerPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default StreamBrokerPrx ice_batchDatagram()
    {
        return (StreamBrokerPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default StreamBrokerPrx ice_compress(boolean co)
    {
        return (StreamBrokerPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default StreamBrokerPrx ice_timeout(int t)
    {
        return (StreamBrokerPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default StreamBrokerPrx ice_connectionId(String connectionId)
    {
        return (StreamBrokerPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default StreamBrokerPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (StreamBrokerPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::MIO::StreamBroker";
    }
}
